# Generated by Django 2.0.1 on 2018-06-28 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='resolved',
            field=models.BooleanField(default=0),
        ),
    ]
