# Generated by Django 2.0.1 on 2018-06-28 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_incident_resolved'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='accidents',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='map.Incident'),
        ),
    ]
